### ISSUE TITLE
TEC Service Doesn't Open the USB Port

### ISSUE THREAD

**Issue by mkardan** [spomjaksilp/pyMeCom#9]
Hi there, 
I have configured the TEC controller with the TEC service before and now I would like to send commands through python. But it seems like the USB port is not open to do that?

Log is attached.

Thank you,

C:\Users\mk\AppData\Local\Programs\Python\Python37\python.exe "C:/Users/mk/Documents/RD_Assignments/1108/TEC 1090/pyMeCom for TEC Controller by spomjaksilp (3)/example.py"
Traceback (most recent call last):
  File "C:/Users/mk/Documents/RD_Assignments/1108/TEC 1090/pyMeCom for TEC Controller by spomjaksilp (3)/example.py", line 106, in <module>
    mc = MeerstetterTEC()
  File "C:/Users/mk/Documents/RD_Assignments/1108/TEC 1090/pyMeCom for TEC Controller by spomjaksilp (3)/example.py", line 45, in __init__
    self._connect()
  File "C:/Users/mk/Documents/RD_Assignments/1108/TEC 1090/pyMeCom for TEC Controller by spomjaksilp (3)/example.py", line 49, in _connect
    self._session = MeCom(serialport=self.port)
  File "C:\Users\mk\Documents\RD_Assignments\1108\TEC 1090\pyMeCom for TEC Controller by spomjaksilp (3)\mecom\mecom.py", line 420, in __init__
    self.ser = Serial(port=serialport, timeout=timeout, write_timeout=timeout, baudrate=baudrate)
  File "C:\Users\mk\AppData\Local\Programs\Python\Python37\lib\site-packages\pyserial-3.4-py3.7.egg\serial\serialwin32.py", line 31, in __init__
  File "C:\Users\mk\AppData\Local\Programs\Python\Python37\lib\site-packages\pyserial-3.4-py3.7.egg\serial\serialutil.py", line 240, in __init__
  File "C:\Users\mk\AppData\Local\Programs\Python\Python37\lib\site-packages\pyserial-3.4-py3.7.egg\serial\serialwin32.py", line 62, in open
serial.serialutil.SerialException: could not open port '/dev/ttyUSB0': FileNotFoundError(2, 'The system cannot find the path specified.', None, 3)

**Comment by timhellwig** [comment]
Hi mkardan,

from the log it looks like you are on a Windows machine. Please take a look at the class MeerstetterTEC in the example and you see that it has an optional argument port that defaults to "dev/ttyUSB0" which is a Linux address to a serial port. You will need to construct the Tec in the main function with your windows  port address.
Best regards,
Tim

**Comment by mkardan** [comment]
Brilliant,  thanks a lot Tim. :)
